### ISSUE TITLE
Stripe plugin is not compatible with the tenancy plugin

### ISSUE THREAD

**Issue by jamal7887** [payloadcms/plugin-stripe#30]
when i start a stripe webhook without the tenancy plugin it works as expected, When I enable the tenancy plugin and try to start the webhook at "localhost:3000/mytenant/stripe/webhooks" for instance I get a 404 error.

**Comment by jacobsfletch** [comment]
Hey @jamal7887 the tenancy plugin you are referring to is probably this one: https://github.com/joas8211/payload-tenancy which is a community plugin. You should open this issue up in that repository instead. Without looking, it could be that this plugin opens some endpoints that interfere with this one. If there's truly an issue with this plugin, feel free to return here with some specific details and I'll be happy to help further 👍

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-stripe) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. Please refer to [this open discussion](https://github.com/payloadcms/payload/discussions/4490) for more details and to continue the conversation. Or feel free to [open a new discussion](https://github.com/payloadcms/payload/discussions) around this, or even [hop on our Discord](https://discord.com/invite/payload) and get help there.
