### ISSUE TITLE
Plugin takes hardcoded env var, not from config

### ISSUE THREAD

**Issue by silveltman** [payloadcms/plugin-stripe#31]
I ran into the issue of the plugin giving an error: 'you did not provide an API key,'.

I had changed my env variable name, which seems to be the cause. The hooks have the env variable hard coded, instead of taking it from the config. This line is in the hooks:

`
const stripeSecretKey = process.env.STRIPE_SECRET_KEY`

**Comment by jacobsfletch** [comment]
Thank you for reporting on this @silveltman 👍

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-stripe) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues will be closed. This issue, however, will be transferred over. Please refer to [this open discussion](https://github.com/payloadcms/payload/discussions/4490) for more details.
